Assignments/chess board
bhs-intro-to-programming/EllisWaterman pull request #13
Opened 2022-11-15 23:33 UTC by EllisWaterman

2022-11-17 19:37 UTC, gigamonkey requested changes
I like where this is going!

2022-11-17 19:37 UTC, gigamonkey commented on assignments/chess-board/code.js
> +  ]
This is an interesting approach that can definitely pay off. You might want to go one step further and include the string with the piece character in these objects. And don't use the properties to encode what piece it is. Something like:

```javascript
const playerWhite = {
  pieces: [
    { piece: WHITE_KING, row: 5, col: 8 },
    { piece: WHITE_KNIGHT, row: 1, col: 4 },
    ... etc.
  ]
}
```

Basically the idea is that you make an array of objects where each object is shaped the same (i.e. has the same properties) and differs only in the values. 

Then you can write a `drawPieces` function that takes these two players and draws all the right pieces at the right positions.

2022-12-01 02:44 UTC, EllisWaterman commented
you can click on pieces and move them. In the board array, the pieces have teams now, so next I will work on taking another team's pieces.

2022-12-01 17:14 UTC, gigamonkey approved these changes
This looks really good. I left a few comments. But go ahead and merge this and then if you want to keep working on it you can make new PRs for your future work.

2022-12-01 17:14 UTC, gigamonkey commented on assignments/chess-board/code.js
> +  board[piece.col][piece.row] = { team: piece.team, icon: piece.icon, col: piece.col, row: piece.row }
I don't think you need to create a new object here since all the values are being copied from the piece you are given. I'd expect this to be:

```javascript
  board[piece.col][piece.row] = piece;
```

2022-12-01 17:14 UTC, gigamonkey commented on assignments/chess-board/code.js
> +  pieces.forEach(piece => {
Nice use of `forEach`.

2022-12-01 17:14 UTC, gigamonkey commented on assignments/chess-board/code.js
> +    board[col][row] = pieceSelected
I feel like these lines should go into `placePiece` and then you should call that function here. And you might want to make a `removePiece` function that both clears out the element of `board` and calls `emptySpace`. That function would be useful if you developed this further to allow for captures, etc. but even if not would make this code a bit clearer.

2022-12-09 22:04 UTC, merged