Assignments/game of life
bhs-intro-to-programming/EllisWaterman pull request #14
Opened 2022-12-12 22:55 UTC by EllisWaterman

2022-12-13 18:45 UTC, gigamonkey requested changes
Looking good but I think the logic isn't quite right.

2022-12-13 18:45 UTC, gigamonkey commented on assignments/game-of-life/code.js
> +    Array(cols).fill().map(() => ({ health: 'dead' })));
While this is a correct use of objects, in this case, where every cell is either alive or dead, I'd probably just use booleans. I.e. set every cell to `false` initially and then switch it to `true` when it is alive. That will simplify the boolean expressions in `doTheLive`.

2022-12-21 19:17 UTC, EllisWaterman commented
I made it work. I looked up delay and switch break statement.

2022-12-30 00:04 UTC, gigamonkey approved these changes
This is very impressive work. There are ways to simplify the code that I may make a video about but everything is very clean and makes sense.

2022-12-30 00:04 UTC, gigamonkey commented on assignments/game-of-life/code.js
> +    switch (location) {
This is a fine way to do it though I suspect there are some underlying mathematical regularities that you could take advantage of. (Though one way to get there might require knowing trig.)

2022-12-30 00:04 UTC, gigamonkey commented on assignments/game-of-life/code.js
> +  setTimeout(go, 100);
Glad you figured this out. Though this framework is set up for animation so you don't actually need to do things this way, you just need to write a function that you can pass to `animate`. But in some ways it's more impressive that you figured this out on your own, presumably from Googling and reading docs. So nice work.

2023-01-04 22:29 UTC, merged