Assessments/2023 02 24 refactoring
bhs-intro-to-programming/EllisWaterman pull request #32
Opened 2023-02-24 23:29 UTC by EllisWaterman

2023-02-26 20:54 UTC, gigamonkey approved these changes
This is close in a lot of ways but because you moved *everything* up to the top level including all the variables, most of your functions use a mix of arguments passed in and references to now global variables. We'll go over this in class but the goal (as it said in the instructions) was to factor things without adding any new global variables.

2023-02-27 00:51 UTC, EllisWaterman commented
I made more functions about draw head, torso, butt. Removed a lot of global variables. I have 15 functions now.

2023-02-28 02:02 UTC, gigamonkey requested changes
You did get rid of some globals and you have more functions with more arguments but there is still more to be done. You should watch the Snowman refactoring video (https://www.youtube.com/watch?v=q82fv09NLjM) to see what I'm talking about.

2023-02-28 02:02 UTC, gigamonkey commented on assessments/2023-02-24-refactoring/code.js
> +  const horizon = height * 0.7
This is in some ways better than having it be global since this is the only function that cares about the horizon. But even better would be to have kept the `drawPicture` function and it's three arguments and have that function pass the value of `horizion` into this function which should accept it as an argument.

2023-03-06 22:52 UTC, merged