Projects/website
bhs-intro-to-programming/EllisWaterman pull request #38
Opened 2023-03-15 22:33 UTC by EllisWaterman

Taking works a bit, a few bugs.

2023-03-16 04:15 UTC, gigamonkey approved these changes
This all looks reasonable. Go ahead and merge this but keep the branch around to keep working on.

2023-03-16 04:15 UTC, gigamonkey commented on projects/website/public/chess.js
The two lines I want to comment on are not part of this most recent change so Github won't let me. 

The first is in `placePieces`:

```javascript
const placePieces = () => {
    pieces.forEach(piece => {
        placePiece(piece);
    });
};
```

Note that when you're calling a higher-order function like `forEach` with a function that just passes its argument on directly no another function like here: `(piece) => placePiece(piece)` you don't need the anonymous function; you can just pass the function you actually want to call, like this:

```javascript
pieces.forEach(placePiece);
```

My other comment was about the second line in `emptySpace`:

```
const emptySpace = (piece) => {
    let color = ((piece.col + piece.row * 7) % 2 === 0) ? 'white' : 'grey';
```

I'm pretty sure the `* 7` isn't doing anything: if `pieces.row` is odd multiplying it by 7 won't change that and likewise if it's even. So you can just write `(piece.col + piece.row) % 2 === 0` which is basically testing that the row and column are either both odd (the sum of two odd numbers is even) or both even (the sum of two even numbers is even).

2023-03-17 02:44 UTC, gigamonkey requested changes
The idea of is good but the code so far in `pawnLegal` is a bit confused. But I'm sure you'll sort it out.

2023-03-17 02:44 UTC, gigamonkey commented on projects/website/public/chess.js
> +    if(square[row][cow] === piece[row][col+1]) {
I'm a bit confused about what `piece` and `square` are. Pieces have `row` and `col` properties, right? But you're using `row` and `col` as variables names and indexing into `square` and `piece` like they are 2d-arrays. Which doesn't seem right.

2023-03-17 02:44 UTC, gigamonkey commented on projects/website/public/chess.js
> +    if (peice.icon === "WHITE_PAWN" || "BLACK_PAWN") {
`piece` not `peice`.

2023-03-19 18:03 UTC, gigamonkey approved these changes

2023-03-19 18:03 UTC, gigamonkey commented on projects/website/public/chess.js
> +    if (piece.icon === WHITE_PAWN || piece.icon === BLACK_PAWN) {
As you get deeper into this you might find that it would be useful to add another property to your piece objects:

```javascript
   { team: 'white', kind: 'pawn', icon: WHITE_PAWN, row: 6, col: 1 }
```

then you can write these tests more simply:

```javascript
    if (piece.kind === 'pawn') {
```

2023-03-21 00:33 UTC, EllisWaterman commented
bishop moves do not work

2023-03-21 02:52 UTC, gigamonkey approved these changes
Good progress though your bishop logic seems a bit sus to me.

2023-03-21 02:52 UTC, gigamonkey commented on projects/website/public/chess.js
> +    }
Remember that whenever you have code in the structure:

```javascript
if (condition) {
  return true;
} else {
  return false;
}
``` 

you can (and should) just write:

```javascript
return condition;
``` 

So in this case the whole function could be written as:

```javascript
const rookMoveIsLegal = (piece, col, row) => {
  return col === piece.col || row === piece.row;
};
``` 

or even in shorthand form:

```javascript
const rookMoveIsLegal = (piece, col, row) => col === piece.col || row === piece.row;
```

2023-03-21 02:52 UTC, gigamonkey commented on projects/website/public/chess.js
> +        if ((col !== piece.col && row !== piece.row)) {
I don't think this is the right condition. If I tried to move a bishop like a knight the new row and column would both be different but it's not a legal bishop move.

2023-03-22 17:33 UTC, gigamonkey approved these changes
Good.

2023-03-22 17:33 UTC, gigamonkey commented on projects/website/public/chess.js
> +    return Math.abs(col - piece.col) === Math.abs(row - piece.row)
That looks right.

2023-03-22 17:33 UTC, gigamonkey commented on projects/website/public/chess.js
> +    return Math.abs(col - piece.col) === Math.abs(row - piece.row) || (col === piece.col || row === piece.row)
Might be nice to write this in terms of the two other functions you wrote:

```javascript
    return bishopMoveIsLegal(piece, row, col) || rookMoveIsLegal(piece, row, col);
```

Saves some typing, removes some chances for typos, and also shows the logic of the situation, queen moves are the combination of bishop and rook moves.

2023-03-22 17:33 UTC, gigamonkey commented on projects/website/public/chess.js
> +    return (row === piece.row + 1 && col === piece.col) ||
This is fine. I'll note that you could probably simplify this if you thought about the absolute value of the differences in the row and column directions and what they can possibly be for a legal king move.

2023-03-24 18:43 UTC, gigamonkey approved these changes
Looks good. Added some comments about simplifying boolean expressions.

2023-03-24 18:43 UTC, gigamonkey commented on projects/website/public/chess.js
> +        if (col === piece.col && row === piece.row + pawnDirection || col === piece.col && row === piece.row + pawnDirectionFirstMove) {
Here and elsewhere you can simplify these boolean expression by factoring out common sub-expressions the same way you might in algebra. For instance anything of the form:

```javascript
(a && b) || (a && c)
```

can be rewritten as:

```javascript
a && (b || c)
```

So in this case you can write:

```javascript
col === piece.col && (row === piece.row + pawnDirection  || row === piece.row + pawnDirectionFirstMove)
```

And then since `pawnDirectionFirstMove` is such a long name and is only used here, I might get rid of that variable and write instead:

```javascript
col === piece.col && (row === piece.row + pawnDirection  || row === piece.row + pawnDirection * 2)
```

And then since we're in the context of a function that's about pawns, I might simplify the name `pawnDirection` to `direction` since it's implicitly about pawns which makes it a bit shorter and, to me at least, easier to read with less words to parse.

```javascript
col === piece.col && (row === piece.row + direction  || row === piece.row + direction * 2)
```

2023-03-29 22:30 UTC, merged

2023-03-31 03:09 UTC, gigamonkey reviewed
more great progress. Sorry I got a bit behind on reviewing.