Assignments/array functions
bhs-intro-to-programming/EllisWaterman pull request #8
Opened 2022-10-18 21:39 UTC by EllisWaterman

2022-10-19 03:37 UTC, gigamonkey requested changes
Overall pretty good! But please fix the two functions I commented on and request another review.

2022-10-19 03:37 UTC, gigamonkey commented on assignments/array-functions/code.js
> +    else
This is not quite right because it will immediately return false if we don't find 101. You can return true as soon as you find one that is greater than 100 but you have to wait until the loop is complete before you can know there are none and can return false.

2022-10-19 21:39 UTC, EllisWaterman commented on assignments/array-functions/code.js
> +    if (x.pop() === 10)
fixed. It now makes another array and modifies that one instead of the original one.

2022-10-20 21:35 UTC, EllisWaterman commented on assignments/array-functions/code.js
> +  for (let numbOver100 = 101; numbOver100 < 10000000; numbOver100++) {
fixed, looks at elements

2022-10-20 21:35 UTC, EllisWaterman commented on assignments/array-functions/code.js
> +    else
fixed

2022-11-04 18:35 UTC, gigamonkey approved these changes
Looks good. Go ahead and merge.

2022-11-04 18:35 UTC, gigamonkey commented on assignments/array-functions/code.js
> +  return Array(n).fill().map((x, i) => i+1).map((x) => Array(x).fill(x)).flatMap((x) => x)
This is good. You can simplify it a bit by collapsing the extra `maps` and using the second argument `i` directly in `flatMap`, something like this:

First collapse the two chained`map`s:

```javascript
return Array(n).fill().map((x, i) => Array(i + 1).fill(i + 1)).flatMap((x) => x);
```

Then collapse the `map` and `flatMap`:

```javascript
const pyramid = (n) => Array(n).fill().flatMap((_, i) => Array(i + 1).fill(i + 1));
```

2022-11-07 01:56 UTC, merged