Assignments/tic tac toe
bhs-intro-to-programming/EllisWaterman pull request #9
Opened 2022-10-30 18:17 UTC by EllisWaterman

2022-11-02 20:12 UTC, gigamonkey requested changes
Overall a very nice job. I left some comments on things you should fix just so you can see how the code looks after making the changes. But I already raised your grade on booleans and basic control constructs on the basis of this project. Please try the changes I suggested and then request another review.

2022-11-02 20:12 UTC, gigamonkey commented on assignments/tic-tac-toe/code.js
> +  if ((winnersSymbol = horizontalWinner()) || (winnersSymbol = verticalWinner()) || (winnersSymbol = diagonalWinner()))
So you're actually relying on the fact that your three winner functions return `undefined` if there's no winner in that direction and the fact that `||` short circuits (i.e. if the left operand  is true it doesn't bother evaluating the right operand. Which is all fine. But given that you can get rid of the variable all together and just write:

```javascript
return horizontalWinner() || verticalWinner() || diagonalWinner();
```

This relies on one fact about `||` that I haven't really taught you which is that it doesn't always evaluate to `true` or `false` but rather to the first "truthy" operand. And `undefined` is "falsey" and any non-empty string is truthy so this works.

2022-11-02 20:12 UTC, gigamonkey commented on assignments/tic-tac-toe/code.js
> +    if (clickCount == 9)
You can bring the `if` up on to the same line as the else and format this like:

```javascript
if (winner !== null) {
  endGame(shape + ' WINS');
} else if (clickCount === 9) {
  endGame('DRAW');
}
```

2022-11-04 14:47 UTC, EllisWaterman commented on assignments/tic-tac-toe/code.js
> +  if (lineType == 'h') {
fixed

2022-11-04 14:47 UTC, EllisWaterman commented on assignments/tic-tac-toe/code.js
> +    if (pos == 0)
fixed

2022-11-04 14:58 UTC, EllisWaterman commented on assignments/tic-tac-toe/code.js
> +const drawWinnerLine = (lineType, pos) => {
fixed

2022-11-04 14:58 UTC, EllisWaterman commented on assignments/tic-tac-toe/code.js
> +  if ((winnersSymbol = horizontalWinner()) || (winnersSymbol = verticalWinner()) || (winnersSymbol = diagonalWinner()))
fixed

2022-11-04 14:59 UTC, EllisWaterman commented on assignments/tic-tac-toe/code.js
> +    if (clickCount == 9)
fixed

2022-11-04 18:25 UTC, gigamonkey approved these changes
Looks good. Go ahead and merge.

2022-11-07 01:55 UTC, merged